
// app/apps/page.tsx
import Link from "next/link";

export const apps = [
    {
        id: "001",
        slug: "001-todo",
        title: "シンプルToDo",
        description: "今日やることをサクッと管理する超シンプルToDoリスト。",
        tags: ["生活", "効率化"],
    },
    {
        id: "002",
        slug: "002-pomodoro",
        title: "ポモドーロタイマー",
        description: "作業時間と休憩時間を設定して使えるシンプルなポモドーロタイマー。",
        tags: ["タイマー", "生産性"],
    },
    {
        id: "003",
        slug: "003-tetris",
        title: "テトリス（ミニ）",
        description: "矢印キーで操作できるシンプルなテトリス風ゲーム。",
        tags: ["ゲーム", "Canvas"],
    },
    {
        id: "004",
        slug: "004-breakout",
        title: "ブロック崩し（ミニ）",
        description: "ボールを跳ね返してブロックを消すクラシックなブロック崩し。",
        tags: ["ゲーム", "Canvas"],
    },
    {
        id: "005",
        slug: "005-requirements-generator",
        title: "要件定義ジェネレーター",
        description: "1行のビジネスアイデアから、FE/BE/DB/非機能要件まで自動分解するAIアプリ。",
        tags: ["AI", "要件定義"],
    },
    {
        id: "006",
        slug: "006-contract-risk-ai",
        title: "契約書リスク抽出AI",
        description: "契約書のテキスト入力またはPDF/Wordアップロードから、主なリスクと修正提案を洗い出すリーガルチェック補助AI。",
        tags: ["AI", "契約書", "リーガル"],
    },
    {
        id: "007",
        slug: "007-ai-ocr",
        title: "AI-OCR 受発注入力",
        description: "注文書（画像/PDF）をアップロードしてAIが自動入力。確認・修正してDB保存する業務効率化ツール。",
        tags: ["AI", "OCR", "業務効率化"],
    },
    {
        id: "008",
        slug: "008-markdown-memo/index.html",
        title: "Markdownメモ",
        description: "リアルタイムプレビューと自動保存機能を備えたシンプルなMarkdownエディタ。",
        tags: ["ツール", "Markdown"],
    },
    {
        id: "009",
        slug: "009-mood-tracker/index.html",
        title: "Mood Tracker",
        description: "その日の気分を5段階で記録して見える化する、メンタル管理アプリ。",
        tags: ["健康", "ライフスタイル"],
    },
    {
        id: "010",
        slug: "010-glucose-habit",
        title: "血糖値スパイク予防習慣サポート",
        description: "食事記録からAIが血糖値スパイクの傾向を解析し、最適な運動アドバイスを提案する生活習慣改善アプリ。",
        tags: ["健康", "AI", "生活習慣"],
    },
    {
        id: "011",
        slug: "011-mario-game",
        title: "マリオ風ゲーム（モック）",
        description: "Phaserを使ったマリオライクなアクションゲームのプロトタイプ。ブロック、敵、ジャンプ、パワーアップ機能を実装。",
        tags: ["ゲーム", "Phaser", "アクション"],
    },
    {
        id: "012",
        slug: "012-voice-memo",
        title: "AI Voice Memo & Summarizer",
        description: "音声入力した内容をテキスト化し、さらにAIが「要約」「ToDo抽出」「マインドマップ化」までしてくれる高度なメモアプリ。",
        tags: ["AI", "業務効率化", "音声認識"],
    },
    {
        id: "013",
        slug: "013-email-drafter",
        title: "Smart Email Drafter",
        description: "シチュエーションと相手を選ぶだけで、失礼のないビジネスメールをAIが代筆してくれるアプリ。",
        tags: ["AI", "ビジネス", "メール"],
    },
    {
        id: "014",
        slug: "014-color-palette",
        title: "AI Color Palette Generator",
        description: "抽象的なキーワードから統一感のある配色パレットを生成し、UIでの使用イメージもプレビューできるデザイナー向けツール。",
        tags: ["AI", "デザイン", "配色"],
    },
    {
        id: "015",
        slug: "015-neon-snake",
        title: "Neon Snake 2025",
        description: "ネオン輝くサイバーパンクな世界観で楽しむ、進化したスネークゲーム。爽快なエフェクトとレスポンシブな操作性。",
        tags: ["ゲーム", "アクション", "Canvas"],
    },
    {
        id: "016",
        slug: "016-typing-racer",
        title: "Typing Speed Racer",
        description: "入力速度に合わせて背景が加速する爽快タイピングゲーム。プログラミング用語を中心にWPMを計測。",
        tags: ["ゲーム", "タイピング", "PC推奨"],
    },
    {
        id: "017",
        slug: "017-2048-ultimate",
        title: "2048 Ultimate",
        description: "中毒性のあるパズルゲーム「2048」の究極版。スマホ操作に最適化されたUIと、心地よいネオン調のビジュアル。",
        tags: ["ゲーム", "パズル", "脳トレ"],
    },
    {
        id: "018",
        slug: "018-world-clock",
        title: "Interactive World Clock",
        description: "美しいグラデーションで世界の時間を体感。都市を追加して時差を一目で確認できます。",
        tags: ["ツール", "時計", "デザイン"],
    },
    {
        id: "019",
        slug: "019-zen-breath",
        title: "Zen Breath",
        description: "リラクゼーションのための深呼吸ガイド。4-7-8呼吸法などで心を整えられます。",
        tags: ["ヘルスケア", "リラックス", "瞑想"],
    },
    {
        id: "020",
        slug: "020-pixel-art",
        title: "Pixel Art Editor",
        description: "スマホで手軽にドット絵作成。16x16のキャンバスでレトロなアイコンを作って保存できます。",
        tags: ["ツール", "アート", "クリエイティブ"],
    },
    {
        id: "021",
        slug: "021-qr-generator",
        title: "QR Code Generator",
        description: "URLやテキストを瞬時にQRコードに変換。色をカスタマイズして、画像として保存できます。",
        tags: ["ツール", "便利", "ジェネレータ"],
    },
    {
        id: "022",
        slug: "022-reaction-test",
        title: "Reaction Time Test",
        description: "画面が緑になったらタップするだけ。あなたの反射神経をミリ秒単位で計測します。",
        tags: ["ゲーム", "測定", "反射神経"],
    },
    {
        id: "023",
        slug: "023-pdf-tools",
        title: "PDFツール",
        description: "PDFの結合・ページ抽出・削除がブラウザ上で完結。サーバーにアップロードしないので安心です。",
        tags: ["ツール", "PDF", "業務効率化"],
    },
    {
        id: "024",
        slug: "024-minesweeper",
        title: "マインスイーパ",
        description: "サイバーなデザインで蘇る定番パズル。スマホでも快適に遊べる操作性を追求しました。",
        tags: ["ゲーム", "パズル", "脳トレ"],
    },
    {
        id: "025",
        slug: "025-decision-roulette",
        title: "ルーレット",
        description: "ランチや罰ゲームなど、迷った時に楽しく決められる決定戦ルーレット。",
        tags: ["ツール", "ライフハック", "運試し"],
    },
    {
        id: "026",
        slug: "026-job-description",
        title: "求人票メーカー",
        description: "求める人物像を入力するだけ。AIが応募したくなる魅力的な募集要項を作成します。",
        tags: ["業務効率化", "AI", "人事"],
    },
    {
        id: "027",
        slug: "027-memory-match",
        title: "神経衰弱",
        description: "記憶力とスピードが勝負。連続正解でスコアが伸びる、爽快カードめくりゲーム。",
        tags: ["ゲーム", "記憶力", "脳トレ"],
    },
    {
        id: "028",
        slug: "028-smart-warikan",
        title: "割り勘電卓",
        description: "「上司多め」「遅刻した人安め」など傾斜をつけて計算し、LINE用のテキストも生成。",
        tags: ["ツール", "ライフハック", "便利"],
    },
    {
        id: "029",
        slug: "029-review-analyzer",
        title: "口コミ分析",
        description: "アンケートやレビュー文をAIが解析。ポジティブ/ネガティブ判定と重要ワードを可視化。",
        tags: ["業務効率化", "AI", "分析"],
    },
    {
        id: "030",
        slug: "030-idle-startup",
        title: "会社経営ゲーム",
        description: "クリックで稼ぎ、社員を雇って自動化。Web制作会社を大きくしていく放置系シミュレーション。",
        tags: ["ゲーム", "シミュレーション", "放置系"],
    },
    {
        id: "031",
        slug: "031-day-scheduler",
        title: "AI Day Scheduler",
        description: "やりたいことと予定を入力するだけ。AIが優先順位を考慮して最適な1日のスケジュールを組み立てます。",
        tags: ["AI", "スケジュール", "タスク管理"],
    },
    {
        id: "032",
        slug: "032-ai-resume-builder",
        title: "AI職務経歴書",
        description: "箇条書きの実績・経歴から、プロフェッショナルな職務経歴書テキストを自動生成。",
        tags: ["AI", "キャリア", "ビジネス"],
    },
    {
        id: "033",
        slug: "033-ai-travel-planner",
        title: "AIトラベルプランナー",
        description: "行き先と日数を入力するだけ。あなたの興味に合わせた旅行プランをAIが提案。",
        tags: ["AI", "旅行", "ライフスタイル"],
    },
    {
        id: "034",
        slug: "034-ai-code-explainer",
        title: "コード解説くん",
        description: "よく分からないプログラムコードを貼り付けると、AIが初心者向けに優しく解説。",
        tags: ["AI", "プログラミング", "学習"],
    },
    {
        id: "035",
        slug: "035-quiz-generator",
        title: "AIクイズ",
        description: "好きなテーマを入力してクイズを自動生成。遊びながら学べるAIゲーム。",
        tags: ["AI", "ゲーム", "学習"],
    },
    {
        id: "036",
        slug: "036-currency-converter",
        title: "通貨コンバーター Pro",
        description: "リアルタイムレートを取得して世界中の通貨を一括計算。リッチなUIの為替電卓。",
        tags: ["ツール", "金融", "便利"],
    },
    {
        id: "037",
        slug: "037-unit-converter",
        title: "単位変換",
        description: "長さ、重さ、温度などを直感的に変換。もうGoogle検索する必要はありません。",
        tags: ["ツール", "便利"],
    },
    {
        id: "038",
        slug: "038-password-generator",
        title: "パスワード生成",
        description: "強度ゲージ付き。安全で覚えやすいパスワードを瞬時に生成。",
        tags: ["セキュリティ", "ツール"],
    },
    {
        id: "039",
        slug: "039-markdown-editor",
        title: "Markdownエディタ",
        description: "スマホでも使いやすい、リアルタイムプレビュー付きのMarkdown執筆環境。",
        tags: ["ツール", "執筆"],
    },
    {
        id: "040",
        slug: "040-regex-tester",
        title: "正規表現テスター",
        description: "マッチする箇所がリアルタイムにハイライトされる、エンジニア向け正規表現チェックツール。",
        tags: ["開発", "ツール"],
    },
    {
        id: "041",
        slug: "041-image-filter-studio",
        title: "Image Filter Studio",
        description: "写真をおしゃれに加工。グレースケールやセピアなど、ブラウザ上でフィルタ処理。",
        tags: ["画像", "クリエイティブ"],
    },
    {
        id: "042",
        slug: "042-beat-maker",
        title: "Beat Maker",
        description: "ブラウザが楽器に。16ステップのシーケンサーでビートを作って遊べる音楽アプリ。",
        tags: ["音楽", "クリエイティブ"],
    },
    {
        id: "043",
        slug: "043-audio-visualizer",
        title: "Audio Visualizer",
        description: "マイク入力に反応して波形が美しく動く、没入感のあるオーディオビジュアライザー。",
        tags: ["音楽", "Canvas", "アート"],
    },
    {
        id: "044",
        slug: "044-color-gradient-mixer",
        title: "Gradient Mixer",
        description: "美しいグラデーションを作成してCSSをコピー。デザイナー必携の配色ツール。",
        tags: ["デザイン", "ツール"],
    },
    {
        id: "045",
        slug: "045-expense-tracker",
        title: "かんたん家計簿",
        description: "日々の支出をサクッと入力。グラフで無駄遣いを見える化。",
        tags: ["生活", "お金", "管理"],
    },
    {
        id: "046",
        slug: "046-water-intake-tracker",
        title: "水分補給ログ",
        description: "水を飲むと波が満ちていく。心地よいアニメーションで水分管理。",
        tags: ["健康", "習慣"],
    },
    {
        id: "047",
        slug: "047-weather-dashboard",
        title: "Weather Dashboard",
        description: "現在の天気と週間予報を美しく表示。アニメーションアイコン付き天気予報。",
        tags: ["生活", "API"],
    },
    {
        id: "048",
        slug: "048-sudoku-game",
        title: "数独",
        description: "シンプルで美しい数独パズル。隙間時間の脳トレに。",
        tags: ["ゲーム", "脳トレ"],
    },
    {
        id: "049",
        slug: "049-tower-stacker",
        title: "Tower Stacker",
        description: "タイミングよくタップしてブロックを積み上げる、ハラハラドキドキのアクションゲーム。",
        tags: ["ゲーム", "アクション"],
    },
    {
        id: "050",
        slug: "050-the-50th-gallery",
        title: "50 APPS Gallery",
        description: "これまでに作った50個のアプリが一堂に会する記念碑的ギャラリー。",
        tags: ["記念", "集大成"],
    },
    {
        id: "051",
        slug: "051-ai-recipe-chef",
        title: "AI Recipe Chef",
        description: "冷蔵庫の余り物を入力。AIシェフが3つの美味しいレシピを提案します。",
        tags: ["AI", "料理", "生活"],
    },
    {
        id: "052",
        slug: "052-ai-gift-advisor",
        title: "AI Gift Advisor",
        description: "相手の属性と予算を入れるだけで、センスの良いプレゼントを提案。",
        tags: ["AI", "プレゼント", "ライフスタイル"],
    },
    {
        id: "053",
        slug: "053-dream-interpreter",
        title: "Dream Interpreter",
        description: "見た夢の内容を話すと、隠された深層心理やメッセージをAIが占い解説。",
        tags: ["AI", "占い", "エンタメ"],
    },
    {
        id: "054",
        slug: "054-ai-debate-partner",
        title: "AI Debate Partner",
        description: "任意のテーマでAIとディベート対決。論理的思考を鍛える壁打ち相手。",
        tags: ["AI", "学習", "チャット"],
    },
    {
        id: "055",
        slug: "055-smart-diary",
        title: "Smart Diary",
        description: "日記を書くだけでAIが感情を分析。毎日のメンタル変化を可視化します。",
        tags: ["AI", "日記", "メンタルヘルス"],
    },
    {
        id: "056",
        slug: "056-json-csv-converter",
        title: "JSON ↔ CSV Converter",
        description: "エンジニア必携。JSONとCSVを相互変換できるシンプルなツール。",
        tags: ["開発", "ツール"],
    },
    {
        id: "057",
        slug: "057-base64-encoder",
        title: "Base64 Encoder",
        description: "テキストや画像をBase64形式にエンコード・デコード。",
        tags: ["開発", "ツール"],
    },
    {
        id: "058",
        slug: "058-text-diff-checker",
        title: "Text Diff Checker",
        description: "2つのテキストの差分を行単位・文字単位で比較してハイライト表示。",
        tags: ["開発", "ツール"],
    },
    {
        id: "059",
        slug: "059-flexbox-playground",
        title: "Flexbox Playground",
        description: "CSS Flexboxの挙動を視覚的に確認しながらコード生成できる学習ツール。",
        tags: ["開発", "学習", "CSS"],
    },
    {
        id: "060",
        slug: "060-meta-tag-generator",
        title: "Meta Tag Generator",
        description: "SEOやSNSシェア用のメタタグを作成し、プレビューで確認。",
        tags: ["開発", "SEO", "ツール"],
    },
    {
        id: "061",
        slug: "061-3d-solar-system",
        title: "3D Solar System",
        description: "ブラウザ上に広がる小宇宙。惑星の軌道を眺める癒やしの空間。",
        tags: ["Canvas", "宇宙", "3D"],
    },
    {
        id: "062",
        slug: "062-particle-life",
        title: "Particle Life",
        description: "シンプルなルールから生まれる複雑な生命のような粒子のシミュレーション。",
        tags: ["Canvas", "シミュレーション", "アート"],
    },
    {
        id: "063",
        slug: "063-ascii-art-generator",
        title: "ASCII Art Generator",
        description: "画像をアップロードして、テキスト文字だけのアスキーアートに変換。",
        tags: ["画像", "ツール", "レトロ"],
    },
    {
        id: "064",
        slug: "064-kaleidoscope",
        title: "Kaleidoscope",
        description: "画像を万華鏡のように美しく回転させて映し出すデジタル・カレイドスコープ。",
        tags: ["Canvas", "アート", "癒やし"],
    },
    {
        id: "065",
        slug: "065-fireworks-simulator",
        title: "Fireworks Simulator",
        description: "夜空に花火を打ち上げる。タップで爆発するインタラクティブな花火大会。",
        tags: ["Canvas", "アート", "リラックス"],
    },
    {
        id: "066",
        slug: "066-typing-defense",
        title: "Typing Defense",
        description: "降ってくる英単語をタイピングして撃墜する防衛ゲーム。",
        tags: ["ゲーム", "タイピング"],
    },
    {
        id: "067",
        slug: "067-simon-says",
        title: "Simon Says",
        description: "光るボタンの順番を記憶して同じように押す、脳トレ記憶ゲーム。",
        tags: ["ゲーム", "脳トレ"],
    },
    {
        id: "068",
        slug: "068-whack-a-mole",
        title: "Whack-a-Mole",
        description: "飛び出すモグラをタップして叩く、ストレス解消アクションゲーム。",
        tags: ["ゲーム", "アクション"],
    },
    {
        id: "069",
        slug: "069-physics-draw",
        title: "Physics Draw",
        description: "線を書いてボールをゴールに導く、物理演算パズル。",
        tags: ["ゲーム", "パズル", "物理演算"],
    },
    {
        id: "070",
        slug: "070-slot-machine",
        title: "Slot Machine",
        description: "コインを掛けてリールを回す、シンプルなスロットシミュレーター。",
        tags: ["ゲーム", "シミュレーション"],
    },
    {
        id: "071",
        slug: "071-loan-calculator",
        title: "ローン返済シミュレーター",
        description: "借入額と金利から月々の返済額を一瞬で計算。家の購入計画などに。",
        tags: ["ツール", "金融", "生活"],
    },
    {
        id: "072",
        slug: "072-japanese-era-converter",
        title: "年号・西暦変換",
        description: "「平成何年だっけ？」を解決。年齢も同時に確認できる和暦変換ツール。",
        tags: ["ツール", "便利", "生活"],
    },
    {
        id: "073",
        slug: "073-habit-calendar",
        title: "Habit Calendar",
        description: "毎日の習慣をチェックして継続を可視化するシンプルハビットトラッカー。",
        tags: ["ツール", "習慣", "自己管理"],
    },
    {
        id: "074",
        slug: "074-white-noise-player",
        title: "White Noise Player",
        description: "集中力を高めるためのホワイトノイズ・ピンクノイズ再生プレイヤー。",
        tags: ["ツール", "健康", "集中"],
    },
    {
        id: "075",
        slug: "075-morse-code-translator",
        title: "Morse Code Translator",
        description: "テキストをモールス信号に変換して音で再生。逆変換も可能。",
        tags: ["ツール", "通信", "学習"],
    },
    {
        id: "076",
        slug: "076-speed-reading-trainer",
        title: "Speed Reading Trainer",
        description: "単語を高速でフラッシュ表示。読書スピードを向上させるトレーニングツール。",
        tags: ["ツール", "学習", "速読"],
    },
    {
        id: "077",
        slug: "077-kanban-board",
        title: "Kanban Board",
        description: "ドラッグ＆ドロップでタスクを管理。シンプルで使いやすいカンバンボード。",
        tags: ["ツール", "効率化", "タスク管理"],
    },
    {
        id: "078",
        slug: "078-markdown-slides",
        title: "Markdown Slides",
        description: "Markdownで書いたテキストを即座にプレゼンテーションスライドに変換。",
        tags: ["ツール", "プレゼン", "Markdown"],
    },
    {
        id: "079",
        slug: "079-image-compressor",
        title: "Image Compressor",
        description: "ブラウザ上で画像を圧縮・リサイズ。サーバーにアップロードしないので安心。",
        tags: ["ツール", "画像", "便利"],
    },
    {
        id: "080",
        slug: "080-password-strength-checker",
        title: "Password Checker",
        description: "パスワードの強度を判定し、解読にかかる時間を推定。強力なパスワード生成も。",
        tags: ["セキュリティ", "ツール"],
    },
    {
        id: "081",
        slug: "081-code-snippet-library",
        title: "Code Snippet Library",
        description: "よく使うコードの断片を言語ごとに保存。開発効率を上げるエンジニア向けツール。",
        tags: ["開発", "ツール"],
    },
    {
        id: "082",
        slug: "082-browser-info-dashboard",
        title: "Browser Info Dashboard",
        description: "UserAgent、画面解像度、通信速度、バッテリーなど、ブラウザから見える情報を一覧表示。",
        tags: ["開発", "ツール"],
    },
    {
        id: "083",
        slug: "083-web-synth",
        title: "Web Synth",
        description: "Web Audio APIを使ったブラウザシンセサイザー。波形を変えて音作りを楽しめます。",
        tags: ["音楽", "クリエイティブ"],
    },
    {
        id: "084",
        slug: "084-dot-art-animator",
        title: "Dot Art Animator",
        description: "16x16のキャンバスでドット絵を描き、パラパラ漫画アニメーションを作成。",
        tags: ["アート", "クリエイティブ"],
    },
    {
        id: "085",
        slug: "085-soundboard",
        title: "Pon-dashi Soundboard",
        description: "「正解」「ブブー」「ファンファーレ」などの効果音をワンタップで再生。配信やイベントに。",
        tags: ["音楽", "ツール"],
    },
    {
        id: "086",
        slug: "086-color-blindness-simulator",
        title: "Color Blindness Sim",
        description: "画像をアップロードして、色覚多様性（P/D/T型）のある方への見え方をシミュレーション。",
        tags: ["画像", "ツール", "アクセシビリティ"],
    },
    {
        id: "087",
        slug: "087-web-cam-effects",
        title: "Web Cam Effects",
        description: "Webカメラの映像にリアルタイムでエフェクトをかけるマジックミラー。",
        tags: ["カメラ", "ツール", "エンタメ"],
    },
    {
        id: "088",
        slug: "088-pomodoro-rpg",
        title: "Pomodoro RPG",
        description: "作業時間でモンスターを倒し、レベルアップするゲーミフィケーション・ポモドーロ。",
        tags: ["ゲーム", "効率化", "RPG"],
    },
    {
        id: "089",
        slug: "089-gravity-sand",
        title: "Gravity Sand",
        description: "砂、水、火などを描いて、物理法則に従って動く様子を眺めるサンドボックス。",
        tags: ["Canvas", "シミュレーション", "癒やし"],
    },
    {
        id: "090",
        slug: "090-typing-ghost",
        title: "Typing Ghost",
        description: "過去の自分の記録（ゴースト）と競争できる、自己ベスト更新型タイピングゲーム。",
        tags: ["ゲーム", "タイピング"],
    },
    {
        id: "091",
        slug: "091-regex-crossword",
        title: "Regex Crossword",
        description: "正規表現がヒントのクロスワードパズル。楽しみながら正規表現をマスター。",
        tags: ["ゲーム", "開発", "パズル"],
    },
    {
        id: "092",
        slug: "092-memory-piano",
        title: "Pitch Trainer",
        description: "流れる音の音階を当てる絶対音感トレーニング。聞き取り能力をゲーム感覚で強化。",
        tags: ["音楽", "学習", "ツール"],
    },
    {
        id: "093",
        slug: "093-clicker-empire",
        title: "Dev Clicker Empire",
        description: "コードを書いて、コーヒーを飲み、エンジニアを雇う。開発会社経営クリッカーゲーム。",
        tags: ["ゲーム", "放置系", "シミュレーション"],
    },
    {
        id: "094",
        slug: "094-virtual-aquarium",
        title: "Virtual Aquarium",
        description: "デジタル水槽で魚を飼う。タップで餌やり、ぼーっと眺める癒やしの時間。",
        tags: ["Canvas", "癒やし", "シミュレーション"],
    },
    {
        id: "095",
        slug: "095-geek-clock",
        title: "Geek Clock",
        description: "「Unix時間」「16進数カラー」「2進数（BCD）」で時を刻む、エンジニアのための時計。",
        tags: ["ツール", "時計", "デザイン"],
    },
    {
        id: "096",
        slug: "096-game-of-life-3d",
        title: "Game of Life 3D",
        description: "3D視点で楽しむライフゲーム。視点を回転させて、複雑なセルの増殖を観察。",
        tags: ["Canvas", "シミュレーション", "3D"],
    },
    {
        id: "097",
        slug: "097-keyboard-event-viewer",
        title: "Key Event Viewer",
        description: "キーボード入力の詳細情報（keyCode, e.keyなど）を可視化する開発者用チェッカー。",
        tags: ["開発", "ツール"],
    },
    {
        id: "098",
        slug: "098-metronome-pro",
        title: "Metronome Pro",
        description: "BPM・拍子設定、アクセント音など、楽器練習に必要な機能を備えたプロ仕様メトロノーム。",
        tags: ["音楽", "ツール"],
    },
    {
        id: "099",
        slug: "099-svg-pattern-generator",
        title: "SVG Pattern Generator",
        description: "パラメータを調整して、CSS背景用のシームレスなSVGパターンを生成・コピー。",
        tags: ["デザイン", "ツール", "SVG"],
    },
    {
        id: "100",
        slug: "100-web-os",
        title: "WEB OS / 100",
        description: "100個目の到達点。ブラウザの中で動くOS風インターフェース。全てのアプリへの入り口。",
        tags: ["OS", "集大成", "100本記念"],
    },
];

export default function AppsPage() {
    return (
        <main className="min-h-screen bg-slate-950 text-slate-50 px-4 py-8">
            <div className="max-w-2xl mx-auto space-y-6">
                <header>
                    <h1 className="text-2xl font-bold mb-1">Webアプリ100本ノック</h1>
                    <p className="text-sm text-slate-300">
                        作ったミニアプリをここに並べていく。まずは #001 から。
                    </p>
                </header>

                <section className="grid gap-4">
                    {apps.map((app) => (
                        <Link
                            key={app.id}
                            href={`/apps/${app.slug}`}
                            className="block rounded-xl border border-slate-800 bg-slate-900/60 p-4 hover:border-emerald-400 hover:bg-slate-900 transition"
                        >
                            <div className="text-xs text-slate-400 mb-1">#{app.id}</div>
                            <h2 className="font-semibold mb-1">{app.title}</h2>
                            <p className="text-xs text-slate-300 mb-2">
                                {app.description}
                            </p>
                            <div className="flex flex-wrap gap-1">
                                {app.tags.map((tag) => (
                                    <span
                                        key={tag}
                                        className="rounded-full border border-emerald-500/40 bg-emerald-500/10 px-2 py-0.5 text-[10px] text-emerald-300"
                                    >
                                        {tag}
                                    </span>
                                ))}
                            </div>
                        </Link>
                    ))}
                </section>
            </div>
        </main>
    );
}
