-- 既存のテーブルを削除して作り直す場合（データは消えます）
drop table if exists extracted_orders;

create table extracted_orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- 基本情報
  order_number text,
  issue_date date,
  
  -- 発注元
  orderer_name text,
  orderer_address text,
  orderer_contact text,
  
  -- 発注先
  supplier_name text,
  supplier_address text,
  supplier_contact text,
  
  -- 納入・支払い
  delivery_date date,
  delivery_place text,
  delivery_method text,
  payment_terms text,
  
  -- 金額
  subtotal_amount bigint,
  tax_amount bigint,
  total_amount bigint,
  
  -- その他
  remarks text,
  
  -- 明細（JSONB）
  items jsonb
);

-- RLS設定
alter table extracted_orders enable row level security;

create policy "Enable read access for all users"
on extracted_orders for select using (true);

create policy "Enable insert access for all users"
on extracted_orders for insert with check (true);
